### PR TITLE
Zombie mode

### PR DESCRIPTION
**Pull request by m-byte**
This is a zombie mode for Ogar. As soon as a player touches a zombie, they also turn into a zombie. Zombies cannot eat each other.

### CODE REVIEW

**Comment by vram4** [comment]
@m-byte So its like a game of tag, nice. You might also want to make it so that the server resets when all players become zombies.

**Comment by m-byte** [comment]
Good idea. I'll look into that. Although, the server will have to pick a new zombie then.

**Comment by maixuanhan** [comment]
This game mode is unbalanced.
It's so easy to become a zombie. Zombie can move very fast. This makes a tiny zombie becoming a huge threat. Please think about the ways to improve that.

**Comment by m-byte** [comment]
What if all zombies grow by the size of every new zombie? That way, they get slower every time a player gets infected...

**Comment by maixuanhan** [comment]
That would not help much because they can eject or split to be smaller. I have some small ideas. Well, after writing them down clearly, it's not small anymore :scream:. 

 1. Make it being a time-based game mode.Time is configurable. In the below requirement, I assume it is 30 minutes.
 1. Game end:
     1. Game ends after 30 mins from starting --> **HUMAN** team wins; or
     1. All players are zombie --> **ZOMBIE** team wins.
 1. Game start:
     1. After server started 1 min; or
     1. After previous game 1 min.
 1. Basic rule:
     1. At the start time, one player will be selected randomly. The selected player is zombie. Other players are human.
     1. Player who joins after game has been started is zombie.
     1. If all zombies are left the game, one randomly selected player will become a zombie.
     1. Two zombies cannot eat each other. Zombie can eat any other cell types as usual.
     1. Zombie can eject mass as usual (or even it can eject more quickly, to feed the victim to make it slower - This is not MANDATORY, refer OPTIONAL requirements section).
     1. Zombie can split but its speed will be decreased a number of times corresponding to its number of cells. (I cannot give the specific formula here, you can adopt some, to see how players react.).
 1. OPTIONAL requirements:
     1. Zombie can eject mass more quickly.
     1. Zombies have color changed continuously on the gray scale.
         ```javascript
         // at start time one becomes a zombie:
         var val = (Math.random() * 256) >> 0;
         zombie.color = { r: val , g: val , b: val };

         // ....

         // onTick or some event:
         var val = zombie.color.r;
         val = (val + 5) % 256;
         zombie.color = { r: val , g: val , b: val };
         ``` 
     1. Game statistic: The first line of Leader Board will be utilized to show the count of **Z**ombie players and the count of **H**uman player. E.g. `35Z / 10H`. The second line shows the total mass of each team (Z team and H team). Other lines show human player names.
     1. There can be a case that a human player reject to eat to keep himself lean, so that he can run away very fast. In order to encourage human player to eat, a new cell type will be introduced: **HERO POISON** (sorry for such a dramatic name, I cannot imagine any name :sweat_smile:).
        * Human player cell eats Hero Poison will become a hero for a short configurable duration (e.g. 1 mins): player's cells can merge immediately, hero cannot be turn into zombie, hero can eat either smaller human or smaller zombie :cool:.
        * When being touched by a zombie, human player's cells become CRAZY human for a short duration (e.g.10 secs): he will be boosted speed (e.g. 1.5 times of normal speed). After that duration of time, 
          * If he doesn't eat any Hero Poison, he becomes a zombie; or,
          * If he can find out and eats a Hero Poison, he turn back to normal human. Note that while being Crazy, he doesn't have any hero abilities, such as immediately merging, eating smaller zombie. (So he's better run after getting the pill :pill:).
        * HERO POISON is limited. E.g. There will be only 2 or 3 cells for the whole map, after being consumed, it will take 5 or 10 mins to spawn a new one.
        * Zombie cannot eat Hero Poison.
     1. **BRAIN** cell type can be introduced also.
        * Human cannot eat Brain.
        * Zombie eat a Brain will be boosted speed (e.g. 1.5 times of normal speed) in 5 or 10 seconds (keep it short, because I've tried this kind of boost, it's powerful :skull:).
        * BRAIN is limited. E.g. The number of Brains will not exceed the number of human players at a time (except the case where brains have already spawned before), after being consumed, it will take 2 or 3 mins to spawn a new one. (recover time is shorter than Hero Poison case).

**Comment by m-byte** [comment]
@maixuanhan This mode is zombie ffa. What you are suggesting would be zombie team. I'll consider implementing it, once I am done with Ogar-client.

From my point of view, zombie ffa should be unbalanced. It's not really a team mode. Instead, it is a mode where you try to stay alive the longest. Adding in timing or preventing users from spawning during a game would probably make sense, though.

**Comment by maixuanhan** [comment]
Okay, it will be better that you go ahead with Zombie FFA, I'll fork this repo and try with Zombie team. :)

**Comment by m-byte** [comment]
@maixuanhan Thanks

**Pull request merged**
