### PR TITLE
Add Player IP to 'playerlist' command

### PR DESCRIPTION
**Pull request by modsfabio**

### CODE REVIEW

**Comment by ryush00** [comment]
:+1:

**Comment by vram4** [comment]
I was thinking about adding this feature but decided not to due to privacy reasons.

**Comment by modsfabio** [comment]
It's normal that Administrators see the IPs of useres. There isn't and shouldm't privacy. Don't you think that?

**Comment by vram4** [comment]
Yeah i guess. On second thought, IPs would be a reliable way to ban someone as well.

**Pull request merged**
